# SPDX-FileCopyrightText: 2021 Anders Rune Jensen
#
# SPDX-License-Identifier: Unlicense

name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  licenses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v1

